### ISSUE TITLE
Could we cut a new release? 

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#100]
Since docker, ejpm and spack all tend to used fixed versions rather than master, could we cut a new release even if it is not perfect enough. 

I mean if "use jana master" is suggested, it means it can be put to a tagged version

**Comment by DraTeots** [comment]
Eve if there going to be a lot of small incremental tags

**Comment by nathanwbrei** [comment]
I just created a 'v2.0.4_candidate' branch from the tip of master. It contains a bunch of weird stuff for the sake of the gluex port, so make sure to test it. Once you are confident it works I'll cut v2.0.4 immediately.

**Comment by DraTeots** [comment]
Ok, I now initialize a dockers build with v2.0.4_candidate and right now is testing master (which probably is still the same). I'll let know ASAP

**Comment by DraTeots** [comment]
I tested master branch as much as I could with no problems. Lets cut the release! We have to do a big release the next week, so a tagged version would be appreciated

**Comment by nathanwbrei** [comment]
Release has been cut, tag is `v2.0.4`.
