### ISSUE TITLE
toStrings improvement

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#11]
I don't know if this is one of the future changes, but I wish toString had a better signature.

I mean this one:
```c++
template<typename T> void AddString(std::vector<std::pair<std::string, std::string> > &items, const char *name, const char *format, const T &val) const;
```

The problem. Suppose I have a class as it is now
```c++
class Whatever {
// ... 
   double x;

    void toStrings(std::vector<std::pair<std::string, std::string> > &items) const override {
	// ...
	AddString(items, "x", "%8.3f", x);
    }
};
```
0. Having to type 'x' twice make it more error prone. 

1. (minor addition) Since the first "x" is a sting, all those fancy analysis and refactoring tools that could help doesn't know that "x" is `x`. E.g. If i rename `x` and its occurrences by refactoring tools, the string "x" probably will not get renamed. +1 small bug.  Ok, to improve this, it is easy to make `NAME_OF` macro. So it looks like: 

```c++
 AddString(items, NAME_OF(x), "%8.3f", x);
```
2. So that order [x], [something], [x] actually bugs me. 

3. Moreover I would prefer to have a longer description too (just in case it will be shown in gui, etc). So It would be nice to have something like:

```c++
ADD_STRING(x, "%8.3f", "[mm] Longer description");  // assuming it is done through macro

// or at least
AddString(items, x, "%8.3f");   // who knows how to achieve this? 
AddString(items, x, "%8.3f", "[mm] Longer description"); 
```

P.S. I'm asking about it after trying to write many (already) classes like:

```c++
        uint64_t      count     ;   // (TTree name o_part_count    )
        uint64_t      id        ;   // (TTree name o_part_id       )
        uint64_t      vtx_id    ;   // (TTree name o_part_vtx_id   )
        uint64_t      pdg       ;   // (TTree name o_part_pdg      )
        uint64_t      trk_id    ;   // (TTree name o_part_trk_id   )
        double        charge    ;   // (TTree name o_part_charge   )
        double        dir_x     ;   // (TTree name o_part_dir_x    )
        double        dir_y     ;   // (TTree name o_part_dir_y    )
        double        dir_z     ;   // (TTree name o_part_dir_z    )
        double        tot_mom   ;   // (TTree name o_part_tot_mom  )
        double        tot_e     ;   // (TTree name o_part_tot_e    )
        double        time      ;   // (TTree name o_part_time     )
        double        pol_x     ;   // (TTree name o_part_polariz_x)
        double        pol_y     ;   // (TTree name o_part_polariz_y)
        double        pol_z     ;   // (TTree name o_part_polariz_z)
```
Now imagine I wrote toStrings method for N such classes without mistakes and then what to rename something and do it without mistakes too...

**Comment by faustus123** [comment]
I certainly agree that toStrings is ugly. My preference is to implement some kind of reflection so this is automated and the user never really has to write a toStrings except in special cases.

I like the NAME_OF suggestion. It allows the user to specify the name via the actual variable name as you say. It would also allow them to put a special name there if they don't want the default. For example, in GlueX we have some names like "E(GeV)"  that makes the headers a little nicer. We also have things like "Nhits" as the name with hits.size() being the value. 

Thanks for taking the time to write this up. We are in the middle of some significant refactoring of the internal queue mechanisms, but will try and get to this as soon as we can.

**Comment by DraTeots** [comment]
I think that even having a nice reflection print out, something like ToStrings should exist as sometimes one really wants to have concise, human readable output. And then "E(GeV)" becomes especially important in this scenario, true. 

Agree that it is more like cosmetics, rather than core feature.

**Comment by nathanwbrei** [comment]
What about this? Nicer signature and it lets us add features later without breaking existing code. 
Plus giving names to things makes them more user friendly. I don't enjoy working with other people's vector<map<pair<...>>>

```cpp
void view(JObjectView& view) const override {
    view.add(x, NAME_OF(x), "%8.3f", "[mm] Longer description");
}

struct JObjectMember { string var_name; string value; string description };

struct JObjectView {
    std::string debug_string() const;
    std::string pretty_string() const;
    void get_members(std::vector<JObjectMember>& out);
}
```
