### ISSUE TITLE
Configuration parameter arrays

### ISSUE THREAD

**Issue by faustus123** [JeffersonLab/JANA2#114]
Gaudi allows algorithm properties to be std::vector types so arrays of values can be specified. JANA should support this as well.

e.g.

std::vector<double> offsets = {1.0, 2.0, 3.0};
japp->SetDefaultParameter("PACKAGE:offsets", offsets , "x, y, and z offests");

**Comment by nathanwbrei** [comment]
I'm adding support for vectors of floats, doubles, and int32's. I'm hesitant to do anything too general because I don't want to support recursive types. Anything else I should add, such as int64's?
