### ISSUE TITLE
JFactoryT::Set potential loss of user toe

### ISSUE THREAD

**Issue by faustus123** [JeffersonLab/JANA2#135]
If a JFactory uses the existing `mData` member of `JFactoryT` to store object pointers as opposed to writing them to a temporary stack vector and then calling `Set()`, then the `mStatus` and `mCreationStatus` members need to updated manually. It might be better for the user to always call `Set(mData)` to ensure all internal flags are updated. However, if they do this, the first thing Set() does is call `ClearData()` which will delete all of the objects in `mData`. This will be a clear opportunity for users to shoot themselves in the foot.

The suggestion is to check if `mData` and `aData` refer to the same vector and only call `ClearData()` if they don't.

**Comment by nathanwbrei** [comment]
It's an easy change to make and it'll definitely reduce bugs and confusion. However, it still feels wrong to allow the user to directly access mData at all. (The only reason mData is not private is for GlueX, which already used this pattern a lot.) I'll make this change now and hope that a solution for the broader design problem emerges later.
