### ISSUE TITLE
Set CMAKE_CXX_STANDARD to the value used by ROOT to avoid `string_view` issues

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/JANA2#138]
In most cases, the user of JANA2 will want to compile JANA2 with the C++ standard that ROOT was compiled with (if they set `USE_ROOT=ON`), see e.g. [ROOT's instructions](https://root.cern/install/build_from_source/#setting-the-c-standard), "ROOT needs to be configured and built with the same C++ standard as the programs that will make use of it."

Currently the default in JANA2 is C++14, while ROOT uses the default of the compiler, e.g. `echo __cplusplus | g++ -E -x c++ - | tail -n1` (i.e. C++14 through g++-10, C++17 in g++-11), and then falls back to C++14 when this cannot be determined.

ROOT does not easily provide the C++ standard it was compiled with through its cmake interface. It can be determined from `root-config --features` which includes `cxx14`, `cxx17` as the case may be. Starting with `find_package(ROOT)` first and setting the default `CMAKE_CXX_STANDARD` based on the output of the `root-config` in the found ROOT prefix may be a sensible approach to avoid compilation issues.

**Comment by faustus123** [comment]
I understand the principle, but worry about a system that silently (or at least automatically) changes the c++ standard based on whether the -DUSE_ROOT=1 flag is set or not. Maybe we should check if we are doing something incompatible and throw an error in that case to force the user to set it properly. We could even add an option like -DUSE_ROOT_CMAKE_STANDARD=1 to do this automatically so you would have a way to get the behavior you describe for CI builds. What do you think?

**Comment by wdconinc** [comment]
It would actually probably be easier to figure out whether `root-config --features` has the same `CMAKE_CXX_STANDARD` value and print a warning (with instruction on how to get and set the correct value)

**Comment by nathanwbrei** [comment]
I think this is a great idea. I'd much rather discover the problem before compiling everything and getting a long and cryptic linker error. I agree with David that we shouldn't automatically change the `CMAKE_CXX_STANDARD`. Instead we should check if `USE_ROOT` is set, and if so, whether JANA's `CMAKE_CXX_STANDARD` matches `root-config --features`. If they don't match, I think the CMake config should loudly fail then and there. @wdconinc, would you be up for implementing this by any chance?

**Comment by wdconinc** [comment]
Sure, https://github.com/JeffersonLab/JANA2/pull/141.

**Comment by nathanwbrei** [comment]
Thanks! We'll get this in the next tagged release.
