### ISSUE TITLE
cmake for packages using jana broken

### ISSUE THREAD

**Issue by faustus123** [JeffersonLab/JANA2#148]
Switching to v2.0.7 for EICrecon now sees a cmake failure. This looks to be due to it no longer providing JANA_INCLUDE_DIR and instead providing JANA_INCLUDE_DIRS. However, this latter one is being set to "JANA_INCLUDE_DIRS-NOTFOUND" even though it seems to find the correct path to the JANAConfig.cmake file. Here is the full list of JANA cmake variables when I try to build EICrecon:

```
-- JANA_CONFIG=/home/davidl/work/2022.07.11.EICrecon/EICTOP/JANA/v2.0.7/lib/cmake/JANA/JANAConfig.cmake
-- JANA_CONSIDERED_CONFIGS=/home/davidl/work/2022.07.11.EICrecon/EICTOP/JANA/v2.0.7/lib/cmake/JANA/JANAConfig.cmake
-- JANA_CONSIDERED_VERSIONS=2.0.4
-- JANA_DIR=/home/davidl/work/2022.07.11.EICrecon/EICTOP/JANA/v2.0.7/lib/cmake/JANA
-- JANA_FOUND=1
-- JANA_INCLUDE_DIRS=JANA_INCLUDE_DIRS-NOTFOUND
-- JANA_LIB=JANA::jana2
-- JANA_LIBRARIES=JANA::jana2
-- JANA_VERSION=2.0.4
-- JANA_VERSION_COUNT=3
-- JANA_VERSION_MAJOR=2
-- JANA_VERSION_MINOR=0
-- JANA_VERSION_PATCH=4
-- JANA_VERSION_TWEAK=0
```

It also looks like it is still calling this version 2.0.4.

**Comment by nathanwbrei** [comment]
Temporary fix in PR #149. A deeper fix is issue #151. Closing this as a duplicate.
