### ISSUE TITLE
cmake: possibly missing target_include_directories for jana2 target

### ISSUE THREAD

**Issue by veprbl** [JeffersonLab/JANA2#151]
It seems like #133 introduced a regression for EICrecon, which was worked around in #149. I think, this slipped through because I was testing my change in an environment where include paths were enforced aside of cmake.

**Comment by veprbl** [comment]
This is not right:
https://github.com/JeffersonLab/JANA2/blob/ece7f9ce69ec1fbcdfde847d522aa6262d60f87a/src/libraries/JANA/CMakeLists.txt#L155-L161
https://github.com/JeffersonLab/JANA2/blob/ece7f9ce69ec1fbcdfde847d522aa6262d60f87a/src/libraries/JANA/CMakeLists.txt#L165
https://github.com/JeffersonLab/JANA2/blob/ece7f9ce69ec1fbcdfde847d522aa6262d60f87a/src/libraries/JANA/CMakeLists.txt#L171
Target properties won't inherit this way.

**Comment by nathanwbrei** [comment]
This should be fixed as of #264
