### ISSUE TITLE
Public access to JEvent::Set

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#155]
Related to #154 

JEvent::Set is publicly open while should only be used for EventSources. Might be very confusing for users that 

```c++
// in one place
event->Set(...);   // Allowed and OK

// in another place
event->Set(...);   // Allowed but is NOT OK
```

Here I intentionally use "one place" and "another place" instead of EventSource and Factory because for new users it is "one place" to look and copy code and "another place" to look and copy code.

**Comment by nathanwbrei** [comment]
Moving this discussion to #254
