### ISSUE TITLE
Use of /tmp/jana_status in JSignalHandler.h conflicts on multi-user system

### ISSUE THREAD

**Issue by johnlajoie** [JeffersonLab/JANA2#164]
When attempting to run eicrecon on a shared system (SDCC at BNL) I was encountering problem like: 

`[ERROR] Unable to open named pipe '/tmp/jana_status' for writing`

and eventually a segmentation fault.  A directory `/tmp/jana_status` already exists and was created by another user. 

With a lot of help from Wouter this tracks down to: 

https://github.com/JeffersonLab/JANA2/blob/master/src/libraries/JANA/CLI/JSignalHandler.h#L23

where this is hard-coded. A workaround might be to use "/tmp/"user"/jana_status", and including something like the process id in the name so a given user could run multiple eicrecon jobs without conflict?

**Comment by nathanwbrei** [comment]
Absolutely. Also, this is controlled by a parameter so you can just set 
```bash
-Pjana:status_fname=/tmp/`whoami`/jana_status
```
on the command line.

**Comment by nathanwbrei** [comment]
We don't actually use this feature much, so we should probably make it easy to disable.

**Comment by nathanwbrei** [comment]
Changed the log level from ERROR to WARN and provided more details so that users won't be misled when they see this message.
