### ISSUE TITLE
jana-this -> thisroot kills /usr/local in PATH

### ISSUE THREAD

**Issue by faustus123** [JeffersonLab/JANA2#174]
When `eic-shell` builds JANA via spack, it does so against a ROOT version also built with spack. The ROOT install directory is in a location that includes a long hash (this is just how spack works). Thus, when the JANA2 build captures that location (via ROOTSYS envar) to put into its own `jana-this.sh` file it includes the hash directory in the path to the `thisroot.sh`. This is all fine and works as intended so that setting up JANA's environment using `jana-this.sh` will also ensure it uses the ROOT version JANA was built against.

The issue comes up in `eic-shell` which includes symbolic links in `/usr/local/` that point back to the spack root install directory (the one with the hash). It then sets the `ROOTSYS` envar to `/usr/local`. The `thisroot.sh` script assumes ROOTSYS points to a version of `ROOT` you no longer want to use and so removes it from`PATH`. i.e. it removes `/usr/local/bin` from PATH. This partially breaks `eic-shell` since things like `/usr/local/bin/cmake` can no longer be found.

It is not clear that this is a JANA issue per se, but it may also not be unique to `eic-shell`. Any system building via spack in a container may run into similar issues. 

I'm not sure of the best solution, but one option is to unset `ROOTSYS` before sourcing `thisroot.sh` in `jana-this.sh`. We could also just set `PATH`, `LD_LIBRARY_PATH`,  and `ROOTSYS` directly and avoid `thisroot.sh` altogether. That though may miss some other important settings.

**Comment by wdconinc** [comment]
This issue is still present.

```
14:52:50 wdconinc@menelaos ~/git/EICrecon (main %=) $ eic-shell 
jug_xl> wdconinc@menelaos:~/git/EICrecon$ echo $PATH
/home/wdconinc/EIC/containers/eic_container/local/bin:/opt/software/linux-debian-x86_64_v3/gcc-12.2.0/root-6.26.06-5nazeuqbdgziwvjeh4wgwklb47wv3jaf/bin:/usr/local/scripts:/usr/local/bin:/opt/spack/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
jug_xl> wdconinc@menelaos:~/git/EICrecon$ source jana-this.sh
jug_xl> wdconinc@menelaos:~/git/EICrecon$ echo $PATH
/opt/software/linux-debian-x86_64_v3/gcc-12.2.0/root-6.26.06-5nazeuqbdgziwvjeh4wgwklb47wv3jaf/bin:/opt/software/linux-debian-x86_64_v3/gcc-12.2.0/jana2-2.0.8-4cczqh34fqkehurjqgdnzez746a7c5p5/bin:/home/wdconinc/EIC/containers/eic_container/local/bin:/opt/software/linux-debian-x86_64_v3/gcc-12.2.0/root-6.26.06-5nazeuqbdgziwvjeh4wgwklb47wv3jaf/bin:/usr/local/scripts:/opt/spack/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
jug_xl> wdconinc@menelaos:~/git/EICrecon$ ddsim
bash: ddsim: command not found
```

**Comment by nathanwbrei** [comment]
Verified that this issue is fixed
