### ISSUE TITLE
Floating pointer parameters tolerance on equality check

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#175]
We have a check that parameter loses equality with itself after stringification: 

```cpp
// Test whether parameter is one-to-one with its string representation.
// If not, we have a problem
if (parse<T>(valstr) != val) {
    LOG_WARN(m_logger) << "Parameter '" << name << "' loses equality with itself after stringification" << LOG_END;
}
```

The problem here is that because of [the nature of floating point numbers implementation](https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html) this warning will **always** be triggered for certain numbers. And that gives kind of false positive warning. 

I would propose 2 variants: 

1. Fix it by checking if values are double or float and using according default tolerance for comparison
2. Or... Add tolerance to parameter definition and check that. IDK if this is somehow better than 1 and not just an over-engineering. 

[Related question](https://github.com/eic/EICrecon/pull/349#issuecomment-1317717844) (On behalf of [Christopher Dilks](https://github.com/c-dilks))

**Comment by faustus123** [comment]
I agree that option 1 is probably the way to go.

**Comment by nathanwbrei** [comment]
Fix is in the main branch and will appear in the next release.
