### ISSUE TITLE
Add field to JParameter to hold original string

### ISSUE THREAD

**Issue by faustus123** [JeffersonLab/JANA2#180]
For EICRecon, there is a proposal (and prototype) that uses the DD4hep parser to convert parameters from something like "3*GeV" into a number like "3". That is then written into the parameter. The question came up of whether we could add another filed to JParameter to hold the original string. This would allow the converted value to be written into the parameter for use while preserving the original user value that includes the units.

**Comment by nathanwbrei** [comment]
@faustus123 What ever came of this? Is this something that someone out there still wants? The idea feels a bit messy to me.

**Comment by faustus123** [comment]
I'm not sure that this has come up again since last year. I think Christopher Dilks may have been the one suggesting this(?)

I agree that it would add complication to the JANA source so we would want to hear a strong argument from someone before committing to it. My guess is that this will end up being handled by the larger configuration database that ePIC has plans to implement and thus, may not need JANA support.

I would suggest closing this. We can make a new issue if needed once we know how the config. DB for ePIC will work.

**Comment by veprbl** [comment]
Might have been a path to resolve https://github.com/JeffersonLab/JANA2/issues/217
