### ISSUE TITLE
Rename JApplication::SetDefaultParameter() to RegisterParameter()

### ISSUE THREAD

**Issue by veprbl** [JeffersonLab/JANA2#188]
Seems like this one doesn't actually set the value as seen by user code. This may confuse users, see discussion around:
https://eic.cloud.mattermost.com/main/pl/u3jy6r89cbnufgsumfxotwm3sh

**Comment by nathanwbrei** [comment]
I mean, it _does_ set the value, if you use it right. 

I agree that RegisterParameter() would be a clearer name. The reason it's named the way it is is for backward compatibility.

**Comment by T-Britton** [comment]
Can’t you wrap SetDefaultParameter? Or Make a RegisterParameter that does the same thing….and still maintain backward compatability?

From: Nathan ***@***.***>
Sent: Monday, February 6, 2023 6:47 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [EXTERNAL] Re: [JeffersonLab/JANA2] Rename JApplication::SetDefaultParameter() to RegisterParameter() (Issue #188)


I mean, it does set the value, if you use it right.

I agree that RegisterParameter() would be a clearer name. The reason it's named the way it is is for backward compatibility.

**Comment by nathanwbrei** [comment]
We sure can. However, I don't want to end up with 10 similarly-named methods floating around which are tacitly deprecated in some projects and not in others. What this means is that if we do this, we should plan to deprecate SetDefaultParameter in GlueX so we can eventually outright delete it.

Also, we have another option, which is to add a more modern version, maybe like so:
```c++
double m_my_weird_param;
m_my_weird_param = JApplication::RegisterParameter<double>("ConfusingDetector:ProtoClusters:my_weird_param", 7.7);
```

I'll bet @wdconinc and @veprbl might even prefer this option.

**Comment by veprbl** [comment]
>  However, I don't want to end up with 10 similarly-named methods floating around which are tacitly deprecated in some projects and not in others.

One could mark the `SetDefaultParameter` as `[[deprecated]]` after a while?

**Comment by nathanwbrei** [comment]
Ideally yes, but that's not enough. We don't want 20MB of deprecation warnings every time we compile, either. If we commit to deprecating the method, we should migrate away from using it as well. Which is fine, but this should definitely be run by the stakeholders first, particularly @faustus123.

**Comment by wdconinc** [comment]
> ```
> double m_my_weird_param;
> m_my_weird_param = JApplication::RegisterParameter<double>("ConfusingDetector:ProtoClusters:my_weird_param", 7.7);
> ```
> I'll bet @wdconinc and @veprbl might even prefer this option.

True, though definitely without the `ConfusingDetector:ProtoClusters:` part (which should come from the factory and not be repeated for every parameter or require the helper variable pattern that is also copied into each factory). But at least this version would have type safety and we wouldn't try to set a `string` to a `vector<double>`... (https://github.com/eic/EICrecon/pull/466/files)

**Comment by nathanwbrei** [comment]
I don't quite see how this new version is any more type safe than the existing one - ultimately we either parse a string with all that entails, or we use a correctly typed default value. But I do like the fact that both inputs (the parsed param and the default param) are arguments, and the output is the return value. Feels slightly more intuitive. If I have to write a docstring that is longer than 4 lines, I see it as a little red flag that maybe my function isn't quite as intuitive as I think it is.

Anyhow, I'm glad you brought up the point about having to redundantly specify the factory prefix when retrieving a parameter. This is something that I'd definitely like to address when we add the "explicit factory wiring" feature that will hopefully supersede JChainFactoryT.

**Comment by wdconinc** [comment]
> I don't quite see how this new version is any more type safe than the existing one

The current approach allows you to make copy-paste errors as fixed in the linked PR:
```cpp
        std::vector<double> u_dimScaledLocalDistXY={1.8,1.8};
        std::string u_adjacencyMatrix = "";

        app->SetDefaultParameter("BEMC:EcalBarrelScFiProtoClusters:dimScaledLocalDistXY", u_dimScaledLocalDistXY);
        app->SetDefaultParameter("BEMC:EcalBarrelScFiProtoClusters:adjacencyMatrix", u_dimScaledLocalDistXY);
```

This is not a copy-paste error that would be likely in the new syntax since the compiler has an explicit type to verify against. Even if you let the compiler deduce the type from the second argument, as below, and then use that as return type, it would enforce that you assign it to a variable of a compatible type, or fail to compile as below.
```cpp
        std::vector<double> u_dimScaledLocalDistXY;
        std::string u_adjacencyMatrix;

        u_dimScaledLocalDistXY = JApplication::RegisterParameter("BEMC:EcalBarrelScFiProtoClusters:dimScaledLocalDistXY", {1.8,1.8});
        u_adjacencyMatrix = JApplication::RegisterParameter("BEMC:EcalBarrelScFiProtoClusters:adjacencyMatrix", {1.8,1.8});
```

It doesn't catch runtime issues at compile time (of course), but this would have caught at least a class of errors of wihch that PR is only one example of. (Other classes: typos in the names, duplicate names after copying,... this isn't a fix to those either).

**Comment by faustus123** [comment]
I don't have a major issue with this. I do think it mostly just shuffles a bit how you can get errors. For example both of these will give similar kinds of compile time errors:

~~~
std::string u_adjacencyMatrix = {1.8, 1.8};
app->SetDefaultParameter("BEMC:EcalBarrelScFiProtoClusters:adjacencyMatrix", u_adjacencyMatrix);

// and 

std::string u_adjacencyMatrix ="";
u_adjacencyMatrix = JApplication::RegisterParameter("BEMC:EcalBarrelScFiProtoClusters:adjacencyMatrix", {1.8,1.8});
~~~

similarly a copy paste like the following would give you the same kind of error as before (i.e. if you only change the name of the parameter after copy):
~~~
        u_dimScaledLocalDistXY = JApplication::RegisterParameter("BEMC:EcalBarrelScFiProtoClusters:dimScaledLocalDistXY", {1.8,1.8});
        u_dimScaledLocalDistXY = JApplication::RegisterParameter("BEMC:EcalBarrelScFiProtoClusters:adjacencyMatrix", {1.8,1.8});
~~~

The design of `SetDefaultParameter` was based on the idea that an algorithm author would do rapid development first and once it was working, they could add one line to expose a parameter to being changed at run time. I don't think the suggested change would be a big hinderance to that type of rapid development so, like I said, I don't have a major objection.

I agree with Nathan that we probably want to support just one pattern so we will likely want to deprecate the `SetDefaultParameter` method. However, we should hold off on marking it as deprecated for now until we are closer to a point where we could address the huge number of warnings this would generate in GlueX code. Thus, we can support both for the time being.

**Comment by faustus123** [comment]
This is addressed in PR# 190

**Comment by veprbl** [comment]
The result of merging my and @wdconinc's proposals is another mismatch in naming and functionality.
If I understand correctly, the new `RegisterParameter` now doesn't register anything, but reads a parameter value with a default value, which would be `GetParameter`.

**Comment by faustus123** [comment]
`RegisterParameter` calls `SetDefaultParameter` so the value passed to it is used to set the default value for the parameter. It returns the actual value that the parameter is set to. If the parameter did not exist before, then `RegisterParameter` creates it and sets both the value and default value to whatever is given to it. 

`GetParameter` returns a pointer to the `JParameter` object itself (nullptr if it doesn't exist). `GetParameterValue` will return  the value of the existing parameter but will throw an exception if it doesn't exist.

Maybe I'm misunderstanding something, but I'm pretty sure this is doing exactly what was suggested. Let me know if it is unclear.

**Comment by veprbl** [comment]
@faustus123 My original concern was that there was a method with a misleading name, not that we are missing a method with the "RegisterParameter" name. After https://github.com/JeffersonLab/JANA2/pull/190, Wouter's concern was addressed, but from my point of view, it left us with one more method with a misleading name.

`GetParameterValue` could be overloaded to accept an optional default parameter, instead of introducing a `RegisterParameter`? Unless semantics of `RegisterParameter` mean that it updates a "default" value somewhere in a global state (which would not be a good design, IMHO).
