### ISSUE TITLE
Do not modify default values in SetDefaultParameter

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/JANA2#189]
Don't apply the command line parser to default parameters.

https://github.com/eic/EICrecon/pull/472#issuecomment-1423574555

**Comment by wdconinc** [comment]
FYI @veprbl

**Comment by faustus123** [comment]
We actually need to apply the parser to numeric default values  (see my comment in above reference EICrecon issue). We should skip it though for strings where it is not needed to avoid issues parsing strings with spaces.

**Comment by faustus123** [comment]
This is addressed by PR #191 .

**Comment by wdconinc** [comment]
Thanks! In general it is preferred to close issues only after the fix is in the default branch. GitHub can do this automatically.
