### ISSUE TITLE
JEvent->Insert fails because Factory is unknown

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#19]
```C++

EventSource::Constructor(...) {
//...
    mFactoryGenerator = new JSourceFactoryGenerator<BeagleTextEventRecord>();
//...
}

EventSource::GetEvent(...) {

    auto text_event_record = new BeagleTextEventRecord();

    auto event = std::make_shared<JEvent>();
    event->Insert(text_event_record);   // <=FAILS
}
```

```C++

template <class T>
inline void JEvent::Insert(vector<T*>& items, const string& tag) const  {
	auto factory = mFactorySet->GetFactory(std::type_index(typeid(T)), tag); // FAILS HERE
}
```

I thought we got it working at least at another branch? What movement was performed wrong so I've got a new whole in my leg?

**Comment by pooser** [comment]
FWIW I ran into this same issue.  I too am unable to utilize the Insert() method via an JEvent object.  I planned to formulate a concrete example this morning however, I suppose those efforts are futile.  In the mean time I was going to attempt utilizing the JFactoryT class.

**Comment by faustus123** [comment]
Hmmm... If I look at the current code, it checks if the GetFactory call fails to find a factory and creates one of the appropriate type if necessary. Could you post more details on the failure message?

**Comment by nathanwbrei** [comment]
Looking into this now

**Comment by DraTeots** [comment]
```
//---------------------------------
// GetFactory
//---------------------------------
JFactory* JFactorySet::GetFactory(std::type_index aObjectType, const std::string& aFactoryTag) const
{
	auto sKeyPair = std::make_pair(aObjectType, aFactoryTag);
	auto sIterator = mFactories.find(sKeyPair);    /// < = Exception is coming from here
	return (sIterator != std::end(mFactories)) ? sIterator->second : nullptr;
}
```

The next in call tree is std::map internals:
```
return _M_t.find(__x);
```

Stack:
```c++
JFactorySet::GetFactory(std::type_index, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const stl_tree.h:2536
JFactorySet::GetFactory(std::type_index, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const stl_map.h:1189
JFactorySet::GetFactory(std::type_index, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const JFactorySet.cc:114
void JEvent::Insert<ej::BeagleTextEventRecord>(std::vector<ej::BeagleTextEventRecord*, std::allocator<ej::BeagleTextEventRecord*> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const JEvent.h:138
void JEvent::Insert<ej::BeagleTextEventRecord>(ej::BeagleTextEventRecord*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const JEvent.h:132
JEventSource_beagle::GetEvent() JEventSource_beagle.cc:119
JEventSource::GetProcessEventTasks(unsigned long) JEventSource.cc:153
JThread::CheckEventQueue() JThread.cc:357
JThread::Loop() JThread.cc:259
<unknown> 0x00007fa2b54b857f
start_thread 0x00007fa2b598f6db
__GI___clone 0x00007fa2b4f1388f
```

**Comment by nathanwbrei** [comment]
Hi everyone, 

As David, Dmitry, and I discussed, it makes more sense to fix this by moving towards our goal rather than maintaining backwards compatibility at the expense of even more technical debt. Therefore, we are making an API change. Specifically, we are changing `JEventSource::GetEvent(...)`
from 
`std::shared_ptr<const JEvent> GetEvent()`

to
`void GetEvent(std::shared_ptr<JEvent>)`

This means that the user is no longer responsible for instantiating and configuring JEvents. All they need to do is set the Event/Run numbers and insert a JObject containing whatever buffer they read. 

The code for this is on the branch "feature_jeventsource_typesig". When Dmitry and/or Eric confirm that this works on their end, we can merge it into master.

**Comment by DraTeots** [comment]
I thought its going to be
```c++
void GetEvent(JEvent& event)
```
I mean, it doesn't matter, but wasn't it one of "gotcha!" during our long discussion?

**Comment by nathanwbrei** [comment]
I remember discussing it with you, but I don't think I've discussed it with David yet. I would personally prefer it (assuming no unforeseen dealbreakers), but I would also prefer keeping the semantics consistent across EventSources, Factories, and EventProcessors. Probably we should change this in a later round, at the same time we fix the weird consts?

**Comment by DraTeots** [comment]
Yes!!!

**Comment by DraTeots** [comment]
So I took 'feature_jeventsource_typesig' branch and it works!
