### ISSUE TITLE
Add option to get multiple events at once from JEventPool

### ISSUE THREAD

**Issue by faustus123** [JeffersonLab/JANA2#193]
As it is currently written, `JEventPool::get()` can only grab a single event and it locks a mutex while doing it. If a `JBlockedEventSource` knows it needs N events, it should be able to grab those in one go with a single mutex lock/unlock.

I'm not sure if this should be an enhancement to the existing get() or a new (getmulti()?) call.

It would be nice to include some doxygen comments describing the "location" parameter of get() while the changes are being made since it is not a very intuitive parameter. Should it have a default value (like the thread id?)

**Comment by nathanwbrei** [comment]
This would be a good thing to improve alongside cleaning up the topology interface like we talked about

**Comment by nathanwbrei** [comment]
The fix for this is in v2.1.0.
