### ISSUE TITLE
Bug in JBlockSourceArrow?

### ISSUE THREAD

**Issue by faustus123** [JeffersonLab/JANA2#196]
Digging around, I noticed some confusing code here:
https://github.com/JeffersonLab/JANA2/blob/cd5cf08be7ef887212cc2415fe21ff0e99404e94/src/libraries/JANA/Engine/JBlockSourceArrow.h#L50

It looks like `lambda_result` is never updated so the if-ladder below will only ever see it set to `Status::Success`. Should the `result` variable really just be using `lambda_result`?

Note that I came across this while trying to figure out why the program ends up in an infinite loop after `JBlockedEventSource::NextBlock` returns `JBlockedEventSource::Status::FailFinished`. I was never able to resolve that so there is still some bug to find. (My temporary workaround is to call `JApplication::Quit(true)` when the file stream is exhausted.

**Comment by nathanwbrei** [comment]
I think you are right. 

All this Arrow::execute code can get tricky while still being structurally quite similar to all the other arrows. So at some point we/I should generalize it correctly.
