### ISSUE TITLE
Generic jana executable runs when no event source specified

### ISSUE THREAD

**Issue by faustus123** [JeffersonLab/JANA2#197]
If I run the generic jana executable with no arguments, it (properly) prints a help message. However, if I give it any argument, it enters the event loop, even if no event sources are supplied. e.g.

~~~
jana -Pdummy=1
~~~

Doing this in JANA v2.0.8 and earlier leads to a seg. fault and stack dump. Not good behavior, but an immediate indicator there was a problem.

Since PR #195 , the seg. fault is cured, but it enters an infinite loop processing "events" and printing the ticker.

The correct behavior will be to print a message that there are no more event sources and exit gracefully. Care must be taken to first load and initialize all plugins since one of those may add an event source.

**Comment by nathanwbrei** [comment]
Fixed in v2.1.0.
