### ISSUE TITLE
Avoid forced vendoring run/link-type dependencies (pybind11)

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/JANA2#199]
In `src/python/externals` there is a vendored `pybind11` dependency. It may be useful to allow the use of a system install of `pybind11`. This allows downstream projects control over the build of `pybind11`, e.g. enabling debug symbols or not. If `pybind11` is a requirement, it may be better to list it as a requirement instead of vendoring it. Typically (in my experience packaging for spack), vendoring is used for things like test dependencies (catch2, googletest) that are not always needed and that are not leaving the build environment.

**Comment by nathanwbrei** [comment]
I believe this was fixed in f23042512f9f279be04ff35bd463049a8573ff15, which has been merged into v2.1.0.
