### ISSUE TITLE
CMake probably produces wrong JANA_LIBRARY value

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#201]
Which makes executables fail if libJANA.so is not on LD_LIBRARY_PATH. 

### What is happening

Cmake has the next setup and the output: 

```cmake
find_package(JANA REQUIRED)
message(STATUS "${CMAKE_PROJECT_NAME}: JANA2 cmake   : ${JANA_DIR}")
message(STATUS "${CMAKE_PROJECT_NAME}: JANA2 includes: ${JANA_INCLUDE_DIR}")
message(STATUS "${CMAKE_PROJECT_NAME}: JANA2 library : ${JANA_LIBRARY}")
# ...
target_link_libraries(target_name ${JANA_LIBRARY})
```

The output: 

```
-- JANA4ML4FPGA: JANA2 cmake   : /home/romanov/eic/soft/jana2/jana2-v2.0.9/lib/cmake/JANA
-- JANA4ML4FPGA: JANA2 includes: /home/romanov/eic/soft/jana2/jana2-v2.0.9/include
-- JANA4ML4FPGA: JANA2 library : JANA::jana2_shared_lib
```

This produces the executable that compiles, but when it is run it fails with libJANA.so is not found. The ldd results: 

```
 ldd /home/romanov/eic/JANA4ML4FPGA/install/bin/jana4ml4fpga
        ...
        libCore.so => /home/romanov/eic/soft/root/root-v6-26-10/lib/libCore.so (0x00007f16af400000)
        libJANA.so => not found
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f16ade00000)
        libm.so.6 => /usr/lib/x86_64-linux-gnu/libm.so.6 (0x00007f16ae119000)
        ...
```

I am not sure that `${JANA_LIBRARY}` has a correct value. I would assume that it should be the full path to libJANA.so, but maybe I am wrong here.

**Comment by faustus123** [comment]
This has been addressed in the recently merged PR #198 so the fix will appear in the next tagged release.
One more related change is planned, but it has to do with better handling of configurations that compile static, shared, or both. That will also be introduced before the next release.

For the interim, you can just set LD_LIBRARY_PATH to include the `${JANA_HOME}/lib` directory and it should work.
