### ISSUE TITLE
`SetDefaultParameter` mangles strings with whitespaces

### ISSUE THREAD

**Issue by veprbl** [JeffersonLab/JANA2#217]
In EICrecon, we end up having to implement workarounds like https://github.com/eic/EICrecon/pull/575, and those are only possible because our problem allows for strings without spaces to be interpreted correctly.

**Comment by faustus123** [comment]
I am unable to track this down fully right now so just writing some notes:

This was brought up previously in [eic/EICrecon PR 472](https://github.com/eic/EICrecon/pull/472) and was addressed in PR #191 . 

It should be getting checked with the test here: https://github.com/JeffersonLab/JANA2/blob/0f4f56b1f0142a1492a28d12b423f2a8a6392fca/src/programs/tests/JParameterManagerTests.cc#L96

It's not clear what is different in EICrecon from the JANA test so will need to be tracked down starting with a reproducing example from there.

**Comment by AyanRoy16** [comment]
Hello @wdconinc , 

We added the test case that shows that a c++ command is correctly parsed when provided as a string input to JParameter. Let me know if there is something that we are missing.
PR:  https://github.com/JeffersonLab/JANA2/pull/248
cc. @nathanwbrei @faustus123
