### ISSUE TITLE
"[FATAL] Detected timeout in worker! Stopping." does not result in a non-zero exit code

### ISSUE THREAD

**Issue by nathanwbrei** [JeffersonLab/JANA2#240]
Original issue filed here: https://github.com/eic/EICrecon/issues/875

This is definitely a bug and not an oversight since we set a non-zero timeout-specific exit code here:
JApplication.cc:234

**Comment by wdconinc** [comment]
FYI, https://github.com/eic/EICrecon/issues/875 closed as not an issue anymore (unsure why).

**Comment by nathanwbrei** [comment]
Unable to reproduce. Feel free to re-open if this pops up again.
