### ISSUE TITLE
Strong types for event number and run number?

### ISSUE THREAD

**Issue by nathanwbrei** [JeffersonLab/JANA2#267]
In EICrecon's JOmnifactory (which will hopefully be backported to JANA2 proper) we have a method signature that clang-tidy rightfully complains about:

```c++
void Process(int64_t run_number, uint64_t event_number) override;
```

One idea is to create strong types for run number and event number. This would clean up a bunch of code that uses these numbers.

Another idea is to add support for arbitrary event key levels. For each level there would be a corresponding `Change*()` callback. This would let us support things like 
- EPICS events
- luminosity blocks  
- helicity reversal cycles (for parity experiments)

**Comment by DraTeots** [comment]
I would argue against strong types for run_number and event_number. One might think that strong types add code clarity. But in reality it works on opposite, when you read it - it is yet another type you have to scroll find origins and digest. You read something like `RunNumber_t or run_number_t run_number` and is, like, is it uint64_t? Is it some struct? Some alias? 

There are definitely benefits of making strong types based on base types, like imagine having an Angle type in geometry, which, being basically an alias to double, might be used everywhere and really bring clarity. But for int64_t run_number and uint64_t event_number, which are actually not used widely, IMO, the tradeoff is not on strong types side.

**Comment by nathanwbrei** [comment]
Closing this issue because we won't be using strong types. Instead of using strong types, the JOmniFactory type signature will eventually accept a `JEventKey` that understands the full event hierarchy.
