### ISSUE TITLE
JException doesn't store the underlying exception

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#277]
As I recall use of JExceptions benefits include better reporting and handling inside JANA2. So it is recommended to use JException and base your own classes on JExpection when working with JANA2. The problem arizes for stubs like this (taken from OmniFactory):

```c++
void Process(const std::shared_ptr<const JEvent> &event) override {
        try {
//...
        }
        catch(std::exception &e) {
            throw JException(e.what());
        }
    }
```

The type of underlying exception sometimes might be the same or more important as e.what() but it gets stripped. I would propose adding something like 

```c++
 throw JException(e);
```
With the corresponding reporting

**Comment by nathanwbrei** [comment]
I personally can't stand how C++ does exceptions at all, compared to literally any other programming language in widespread use. I think Cling actually makes them a lot better, and our JException and JBacktrace is a weak approximation of that. If you have any flashes of inspiration as to how you'd improve JExceptions, feel free to share
