### ISSUE TITLE
Get access to factories from JFactorySet

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#28]
```cpp
protected:
	
		//string: tag
		std::map<std::pair<std::type_index, std::string>, JFactory*> mFactories;
```
In particular I needed to find all tags for a factory. Or get all factories names

**Comment by nathanwbrei** [comment]
I assume this is a once-per-program-execution thing, and not a once-per-event thing? 
I could imagine putting together a general TopologySummary POD object reporting exactly what components are present in the system, analogous to JPerfSummary/JArrowPerfSummary. 

For instance:

`
struct FactorySummary { string plugin_name; string type_name; string factory_tag };
struct EventSourceSummary { string plugin_name; string type_name; string source_name };
struct EventProcessorSummary { ... }

class ComponentSummary {
    vector<FactorySummary> factories;
    vector<EventSourceSummary> sources;
    vector<EventProcessorSummary> processors;
}

unique_ptr<const ComponentSummary> JApplication::GetComponentSummary();
`
Thoughts?

**Comment by DraTeots** [comment]
I like when APIs have such summaries!

**Comment by nathanwbrei** [comment]
I've implemented this on a separate branch, feature_jstatus. This is one of the prerequisites for issue #22, so there should be more discussion there. You can get a component summary via JApplication::GetComponentSummary(), and you can also get a list of all factories for an arbitrary JFactorySet via JFactorySet::Summarize(). I'm working on integrating this info into a general 'status' screen which extends/improves JStatus.
