### ISSUE TITLE
Jana doesn't report errors with plugin loading

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#29]
In case there is a problem with .so file JPluginLoader I see that this code:

```
    // Open shared object
    void* handle = dlopen(soname.c_str(), RTLD_LAZY | RTLD_GLOBAL | RTLD_NODELETE);
    if (!handle) {
        LOG_DEBUG(_logger) << dlerror() << LOG_END;
        throw "dlopen failed";
    }
```

Goes to ```  LOG_DEBUG(_logger) << dlerror() << LOG_END;``` but nothing is displayed. 

run parameters:

```
-Pplugins=open_charm,hepmc_reader
-Popen_charm:e_beam_energy=5
-Popen_charm:ion_beam_energy=100
-Popen_charm:smearing=1
-Pnevents=200
-Pnthreads=1
-PJANA:DEBUG_PLUGIN_LOADING=1
-PJANA:VERBOSE=10
-PJANA:EXTENDED_REPORT=1
-PJANA:TASK_POOL_DEBUGLEVEL=1
/mnt/c/eic/data/herwig6_e-p_5x100.hepmc
```

**Comment by DraTeots** [comment]
Looks like exceptions raised in EventSources are swallowed too

**Comment by nathanwbrei** [comment]
Again? This calls for unit tests.

**Comment by nathanwbrei** [comment]
Here's the current situation re exceptions in EventSources:
Old engine: Apparently still swallowed
New engine:  Not swallowed as of 6d4bff57. Also not handled by anybody, they simply terminate the program. (Obviously we should be catching them and document them at some level)

**Comment by nathanwbrei** [comment]
I added test cases verifying that user exceptions don't get swallowed from a variety of places, and this is already on master, see d327f4. I've shrunk the number of places in the code where we print an error message and call JApplication::Quit(), but we still don't have a unified error handler. The main remaining challenge is forwarding exceptions from worker threads back to the master thread when we are running in blocking mode, and cleanly shutting down all workers when one of them has a fault.
