### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#316]
When building jana from tar.gz (downloaded from github) CMake output reports this: 

```
-- -----------------------
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
-- Generating JVersion.h
```

I used

https://github.com/JeffersonLab/JANA2/archive/refs/tags/v2.2.1-rc1.tar.gz

The version was wrong: 

```bash
> jana --version
JANA2 version:  2.2.0
```
It is probably not fatal as jana builds and runs after this. IDK if the version was wrong because of RC or because of the problem above.

**Comment by nathanwbrei** [comment]
The wrong version number is because I forgot to update the version number in the CMakeLists when cutting the last release. It's unrelated to all of the spurious error messages you are seeing.
