### ISSUE TITLE
janadot writes nearly empty dot file

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/JANA2#324]
```console
$ eic-shell
$ jana -Pplugins=JTest,janadot -Pjana:nevents=100
...
Opening output file "jana.dot"

Factory calling information written to "jana.dot". To create a graphic
from this, use the dot program. For example, to make a PDF file do the following:

   dot -Tpdf jana.dot -o jana.pdf

This should give you a file named "jana.pdf".
...
```
but
```console
$ cat jana.dot
digraph G {

        "CreationTime" [shape=box,style=filled,color=white, label=<<font point-size="10">Created: Thu Jul 25 17:05:39 2024</font>>, margin=0];
        {rank=source; "CreationTime";}
        {rank=sink; }
}
```

This issue is present in 2.2.1-rc1 (current version in eic-shell).

**Comment by wdconinc** [comment]
@nathanwbrei Any ideas what might have caused this? I don't see any culprits, but happy to run some tests.

**Comment by wdconinc** [comment]
$ git bisect skip
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
05950b0a2064b9d121721a70aedaccfc3ed7c0cb
c3c2d27a2720e4b6c307a05d97d0100544800ce8
6f60aae97a64b42e4fe90ad7fde86eebca0f321f
c52ade08d10e007ee665a2fd114205cc29934e11
ac784bb7845c625d66bac67cfc68f1daf028878c
b862bd6d1339cdfe13fe40493a63c6d64f1bc1f9
e2b29823926472984d85b5b0a90db4fb82a1dacc
We cannot bisect more!

**Comment by wdconinc** [comment]
This is caused by https://github.com/JeffersonLab/JANA2/pull/283.

**Comment by nathanwbrei** [comment]
Temporary fix is setting the parameter `record_call_stack=1` when running janadot. 

Root cause is that the initialization sequence of JComponentManager currently reads the `record_call_stack` parameter before janadot has a chance to set it.

**Comment by wdconinc** [comment]
Thanks! I was just going to add `record_call_stack=1` to EICrecon today, but maybe I can just upgrade to 2.3.1 :-)
