### ISSUE TITLE
Test if factory with this tag exists

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#37]
One of the problems after the last update is this:

1. There is a plugin, that does "smearing" - fast simulation. It might be enabled or not. 
2. There is another plugin, that checks if "smeared" data is available and uses it, otherwise it uses "raw" data. 

The check was like this:

```c++
if(event->GetFactory<McGeneratedParticle>("smear")) {
     gen_parts = event->Get<McGeneratedParticle>("smear");
     smeared_taken = true;
} else {
    gen_parts = event->Get<McGeneratedParticle>();
    smeared_taken = false;
}
```

Now it throws on 

```c++
if(event->GetFactory<McGeneratedParticle>("smear")))
```

```
`- JException::JException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (0x55802c992580)
      `- JFactoryT<minimodel::McGeneratedParticle>* JEvent::GetFactory<minimodel::McGeneratedParticle>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (0x7f395c5286f0)
       `- JFactoryT<VMesonInputParticle>::Process(std::shared_ptr<JEvent const> const&) (0x7f395c51f6fe)
        `- JFactoryT<VMesonInputParticle>::GetOrCreate(std::shared_ptr<JEvent const> const&) (0x7f395c52b050)
         `- std::vector<VMesonInputParticle const*, std::allocator<VMesonInputParticle const*> > JEvent::Get<VMesonInputParticle>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (0x7f395c527780)
          `- VectorMesonProcessor::Process(std::shared_ptr<JEvent const> const&) (0x7f395c51cfb8)
           `- JEventProcessorArrow::execute(JArrowMetrics&, unsigned long) (0x55802c9a192e)
            `- JWorker::loop() (0x55802c9ac9d9)
             `- /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x7f396ab4e66f)
              `- /lib/x86_64-linux-gnu/libpthread.so.0 (0x7f396a6616db)
               `- clone (0x7f396a38a88f)
```

How to test if the data of particular "tag" exists?

**Comment by nathanwbrei** [comment]
That's not a deliberate API change, it's just an oversight coming from heavy refactoring with light test coverage. For the time being I'm reverting the behavior to what it was before. 

Stylistically I'm not the biggest fan of returning a null pointer when the factory is absent. I'd rather do something more modern which forces the user to acknowledge the 'missing' case, e.g. std::optional. At the moment I'm at a loss how to do so given our constraints. Any suggestions? We have this problem all over the place.

**Comment by DraTeots** [comment]
I believe, the only good option here is to convince David, that bringing [this single header](https://github.com/TartanLlama/optional) is OK. 

* It works from C++11 gcc 4.8 (default on our systems). 
* It is a single header. 
* The license is good. 
* The syntax is nice and easy to read even if one is not familiar

I miss this very much in Jana. That would solve so many problems.

**Comment by nathanwbrei** [comment]
This was fixed a long time ago. I had kept it open just in case we revisited the idea of using std::optionals in our API.
