### ISSUE TITLE
Component Summary YAML printed unconditionally from JApplication

### ISSUE THREAD

**Issue by veprbl** [JeffersonLab/JANA2#373]
This is printed on JApplication start and after exception in JANA 2.3.2. This unsolicited information causes lots of inconvenience. Can we, please, remove it?

**Comment by nathanwbrei** [comment]
Good news! It's been removed since https://github.com/JeffersonLab/JANA2/commit/8ed069da7f307d12cafd6b075eae8401aec6f5aa. You just have to wait until the next release

**Comment by veprbl** [comment]
Thanks!
