### ISSUE TITLE
Using something like std::optional

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#39]
Just thought it is so important, that it deserves a new ticket. Would be nice to get to a decision on optional. It will change not only Jana landscape but also subsequent packages

Just to recap, I proposed to use this single header lib:
https://github.com/TartanLlama/optional

    It works from C++11 gcc 4.8 (default on our systems).
    It is a single header.
    The license is good.
    The syntax is nice and easy to read even if one is not familiar

I'm not insisting on it. I'm insisting on some clear decision =)

**Comment by faustus123** [comment]
IMHO, this is something that is too close to a c++ standard feature to include as part of JANA. I don't want to confuse people familiar with std::optional by causing them to have to seek out documentation on this alternative.
