### ISSUE TITLE
Performance optimization of streamDet plugin

### ISSUE THREAD

**Issue by nathanwbrei** [JeffersonLab/JANA2#43]
Observed throughput of streamDet is in the Hz, but needs to be in the kHz. Some performance improvements have already been made on the feature_zmq_etc branch, but need to be merged into master.

**Comment by faustus123** [comment]
Markus reported privately to me yesterday that this seemed to have been resolved by Eric before he left. There was apparently significant slow downs due to writing to root and csv files. When they removed that, he said that had rates in excess of 4kHz.
