### ISSUE TITLE
Make -PPARAMETER case independent

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#5]
Lets allow users to choose if it fits better for them to type

```bash
# 1
jana -PCATEGORY:PARAMETER1 -PONEMORE:EINIGEPARAMETER -PTRUEPART:FALSEPART ...

# 2 or
jana -pCategory:Parameter1 -pOneMore:EinigeParameter -PTruePart:FalsePart

# 3 or even  (same unreadable as #1 but no caps_lock or shift holding is needed)
jana -pcategory:parameter1 -ponemore:einigeparameter -ptruepart:falsepart
```
The idea of the feature is to treat all 3 examples as the same parameter combination (as they actually address the same thing).  

Don't see a reason for parameter names to be case sensitive. But it seems that readability of many arguments command line or a config file with a lot of parameters may be much improved if we can make parameters case insensitive + less typos from users. 

The change is just about casting to_lower/to_upper right before the string comparison in the parameter manager.

**Comment by faustus123** [comment]
I agree. It is likely to prevent many more mistakes by making them case insensitive than increase functionality
by keeping it case sensitive.


Regards,
-David

-------------------------------------------------------------
David Lawrence Ph.D.
Staff Scientist, Thomas Jefferson National Accelerator Facility
Newport News, VA
davidl@jlab.org<mailto:davidl@jlab.org>
(757) 269-5567 W
(757) 746-6697 C


On Mar 2, 2019, at 10:43 PM, Dmitry Romanov <notifications@github.com<mailto:notifications@github.com>> wrote:


Lets allow users to choose if it fits better for them to type

jana -PCATEGORY:PARAMETER1 -PONEMORE:EINIGEPARAMETER -PTRUEPART:FALSEPART ...
# or
jana -pcategory:parameter1 -ponemorey:einigeparameter -ptruepart:falsepart
# or even
jana -pCategory:Parameter1 -pOneMore:EinigeParameter -PTruePart:FalsePart

The idea of the feature is to treat all 3 examples as the same parameter combination as they actually address the same thing.

Don't see a reason for parameter names to be case sensitive. But it seems that readability of a many arguments or config file with a lot of parameters may be much improved if we can make parameters case insensitive + less typos from users.

The change is just about casting to_lower/to_upper right before the string comparison in the parameter manager.

**Comment by faustus123** [comment]
This has now been implemented with pull request #10. The change only affects the keys used to store the parameters internally in the JParameterManager. Users will still see their original case structure when asking a JParameter for it's name or when the list of parameters is printed.

**Comment by DraTeots** [comment]
Shouldn't `-p` and `-P` work the same?

**Comment by faustus123** [comment]
Oops! I missed that part of your OP.

I’m personally not inclined to make the switch character itself case insensitive. I’d rather
give an error that “-p” is an unknown option. The reason being that there may be other
characters where we wish to use the upper case as one option and the lower case as
another. This is not at all uncommon in my experience.

JANA 1 is not optimal in how it tends to ignore unknown options. The thought was that
it allowed users who wrote their own program to add options unknown to JApplication
but still conveniently pass the nargs, argv parameters into the JApplication constructor.
We should probably make it more strict or at least have some additional option we pass
to the JANA options parser that specifies whether it should be strict.

Regards,
-David

-------------------------------------------------------------
David Lawrence Ph.D.
Staff Scientist, Thomas Jefferson National Accelerator Facility
Newport News, VA
davidl@jlab.org<mailto:davidl@jlab.org>
(757) 269-5567 W
(757) 746-6697 C


On Mar 20, 2019, at 5:19 PM, Dmitry Romanov <notifications@github.com<mailto:notifications@github.com>> wrote:


Shouldn't -p and -P work the same?

**Comment by DraTeots** [comment]
David, I absolutely agree with you on parameters in general. It just feel a little awkward compared to all modern console apps/scripts that the "main" arguments "-P" should be capital (i.e. typed with shift key pressed). I assuming here that you want to have a compatibility with previous JANA version when we'll move HallD soft to JANA2. So I think that having -p and -P acting the same is good. Any other parameters should be case sensitive, I agree with you!

**Comment by faustus123** [comment]
Good point. I think we are in agreement then. We can make -p or -P work for parameters to maintain
backward compatibility but not make that a general rule for all command line switches.


Regards,
-David

-------------------------------------------------------------
David Lawrence Ph.D.
Staff Scientist, Thomas Jefferson National Accelerator Facility
Newport News, VA
davidl@jlab.org<mailto:davidl@jlab.org>
(757) 269-5567 W
(757) 746-6697 C


On Mar 22, 2019, at 1:59 PM, Dmitry Romanov <notifications@github.com<mailto:notifications@github.com>> wrote:


David, I absolutely agree with you on parameters in general. It just feel a little awkward compared to all modern console apps/scripts that the "main" arguments "-P" should be capital (i.e. typed with shift key pressed). I assuming here that you want to have a compatibility with previous JANA version when we'll move HallD soft to JANA2. So I think that having -p and -P acting the same is good. Any other parameters should be case sensitive, I agree with you!
