### ISSUE TITLE
Unknown exception in JEventSource::GetEvent()

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#52]
Hi! 
When I'm doning like this in the event source:

```c++
try {
   foo = std::stod(event_tokens[1]);
}
catch(std::exception &ex) {
   auto err_msg = fmt::format("Error parsing event at line '{}', parsing error message is: {} ", this->started_at_line, ex.what());
   throw std::runtime_error(err_msg);
}
```

JANA2 creates an output:

```
[FATAL] JWorker: Exception: Unknown exception in JEventSource::GetEvent()

  Plugin:         lund_reader.so
  Backtrace:

     `- make_backtrace(std::ostream&) (0x55c48eb60d26)
      `- JException::JException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (0x55c48eb6128d)
       `- JEventSourceArrow::execute(JArrowMetrics&, unsigned long) (0x55c48eb885fa)
        `- JWorker::loop() (0x55c48eb8cad6)
         `- /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x7f3160ee266f)
          `- /lib/x86_64-linux-gnu/libpthread.so.0 (0x7f31609f56db)
           `- clone (0x7f316071e88f)
```

**Comment by faustus123** [comment]
I just put in a pull request that will catch std::runtime_error exceptions and print the contained message. I tested it by temporarily having JTest throw an exception from the event source and it worked.

As a note, it would be preferable to throw a JException which also accepts a string, but carries additional information on the origin of the exception.

**Comment by DraTeots** [comment]
Ok! Didn't know this JException functionality

**Comment by DraTeots** [comment]
It it fixed? 

In tag 2.0.2 I have the same issue. And unfortunately can't do anything about JException as it happens in external lib.
