### ISSUE TITLE
Valgrind shows a memory leak at JArrowProcessingController::measure_internal_performance

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#55]
Did run ejana through a valgrind, it found 2 "DefinatelyLost" at JANA2 JArrowProcessingController::measure_internal_performance()

![image](https://user-images.githubusercontent.com/4732545/76043856-b21f1980-5f26-11ea-8fbf-bc8280324cd5.png)

I looked at the code and didn't understand what is leaking there, actually.

**Comment by nathanwbrei** [comment]
I'm able to reproduce this. Still working on figuring out the cause.

**Comment by nathanwbrei** [comment]
Fixed all memory leaks valgrind and AddressSanitizer could find.
