### ISSUE TITLE
Exceptions thrown in JEventProcessor::Process method aren't displayed or anything

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#6]
Minimal to reproduce: 

```c++
void JEventProcessor_trk_eff::Process(const std::shared_ptr<const JEvent>& event)
{
	fmt::print("Print something\n");
	throw std::runtime_error("Hohoh");
}
```

The processor prints "Print something\n" but thrown exceptions don't stop JANA nor are printed.

**Comment by nathanwbrei** [comment]
Suppressed exceptions are now logged. 
Do we want them to terminate the execution? I don't have an opinion yet.

**Comment by DraTeots** [comment]
I think, that exceptions terminating the execution is good! If an exception went out of plugin it means it is exceptional, the process should be terminated and the developer is bugged by users. 

If users want exception to be silenced it is their responsibility to set `try...catch`. Otherwise nobody really reads the logs (when you have 20+ plugins putting something there) and swallowing exceptions leads to more sophisticated  bugs or unpredictable results in MOST of the cases. 

P.S. Anecdote. From the last Thursday until late Monday we hunted "New version of Geant4 behave strange with one of the volumes". It happened that a magnetic field rotation matrix was deleted right after its initialization and Geant4 swallowed that broken pointer exception. If only it crashed instantly... And I have a lots lots more cases to tell. Frameworks should log and instantly fall on unhanded exceptions.

**Comment by DraTeots** [comment]
This became VERY annoying bug. Could you fix it ASAP, please? 

Thanks!

**Comment by faustus123** [comment]
I just merged a pull request into master that fixes this issue. The problem was due to an improper user of std::future that never called the "get()" method. The future was catching the exception and holding it until get() was called at which time it would re-throw the exception. Since we never called get(), the exception was just ignored.

**Comment by DraTeots** [comment]
Thanks David! I will check it now.
