### ISSUE TITLE
Feature request: Ability to run JANA2 workers via an external thread pool

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#63]
Preface. What JANA does with grace - is ability of different people to work on different plugins (read it as solving different problems) pretty much independently. I believe, that one of the major requirement for full simulation framework is the ability to work on subdetectors in a way one can work on Jana plugins. Geant 4 is absolutely not modular. But it provides its own model of parallelism with thread workers, contexts and 10 years of thinking of what should be global and local, and stuff like that. 

Thinking of it more and more, I understand, so If I where to upgrade G4E to be modular (with subdetectors and components as independent dynamically loaded modules) I would take a lot of functionality already written in JANA (like plugin loading, and even Factories and stuff like that)  but leave multi threading and application driving part on Geant. 

That would probably require something like driving jana workers by external workers (and binding one to other). How hard would it be?

**Comment by faustus123** [comment]
Hi Dmitry,

  Sorry that I’m just now getting to this. I’m going through e-mails in reverse order from when you sent them!

It sounds like you’re interested in using JANA just to load plugins and perhaps have JEventProcessors that
could be called from the threads Geant4 manages. Is this correct?

Certainly you could call anything from the InitPlugin routine including setting up detectors and scorers in a
Geant4 program. For the rest it might be useful if you could draw either a diagram or write some psuedo-code
and then schedule a video chat with Nathan and I to discuss it. I’m trying to keep my calendar up to date
so feel free to find a time there.

Regards,
-David

-------------------------------------------------------------
David Lawrence Ph.D.
Staff Scientist, Thomas Jefferson National Accelerator Facility
Newport News, VA
davidl@jlab.org<mailto:davidl@jlab.org>
(757) 269-5567 W
(757) 746-6697 C


On Mar 20, 2020, at 5:01 PM, Dmitry Romanov <notifications@github.com<mailto:notifications@github.com>> wrote:



Preface. What JANA does with grace - is ability of different people to work on different plugins (read it as solving different problems) pretty much independently. I believe, that one of the major requirement for full simulation framework is the ability to work on subdetectors in a way one can work on Jana plugins. Geant 4 is absolutely not modular. It provides its own model of parallelism with thread workers, contexts and 10 years of thinking of what should be global and local, and stuff like that.
Geant 4 is also absolutely not modular.

Thinking of it more and more, I understand, so If I where to upgrade G4E to be modular (with subdetectors and components as independent dynamically loaded modules) I would take a lot of functionality already written in JANA (like plugin loading, and even Factories and stuff like that) but leave multi threading and application driving part on Geant.

That would probably require something like driving jana workers by external workers (and binding one to other). How hard would it be?

**Comment by nathanwbrei** [comment]
As of #385, workers may be managed by an external thread team, and test cases may simulate individual workers checking tasks in and out with different orderings.
