### ISSUE TITLE
MiniPlugin cmake version

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#65]
Get an error trying MiniPlugin

```
CMake Error at /home/romanov/eic/jana/jana-v2.0.2/lib/cmake/JANA/JANAConfig.cmake:31 (include):
  include could not find load file:

    /home/romanov/eic/jana/jana-v2.0.2/lib/cmake/JANA/MyProject-targets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:5 (find_package)


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.15)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
```

**Comment by nathanwbrei** [comment]
I'm splitting MiniPlugin into MiniProjectPlugin and MiniStandalonePlugin. One has a full CMakeLists including cmake_minimum_required, find_project(JANA), etc. The other has a sparse CMakeLists and assumes these come from the project's root CMakeLists. The cc file is the same for either.

**Comment by nathanwbrei** [comment]
StandalonePlugin (and everything else) is finding JANA via FindJANA.cmake, whereas MiniStandalonePlugin is finding it via JANAConfig.cmake, which is misbehaving. For now I'll make MiniStandalonePlugin do the same thing as StandalonePlugin, and update both of them to use JANAConfig.cmake later.

**Comment by nathanwbrei** [comment]
After talking with David, I'm refactoring our zoo of different plugin generators into a single one which takes a bunch of arguments instead.

**Comment by nathanwbrei** [comment]
JANAConfig.cmake now exports both targets and cmake variables such as `JANA_INCLUDE_DIR`, and no longer has the silly bug. I still don't entirely understand how CMake targets work, but at any rate we definitely don't need (or want) FindJANA.cmake anymore. Thus I am removing the FindJANA.cmake script from both the JANA source code and from `jana-generate.py`. This has the bonus effect of making `jana-generate.py` a bit simpler. I'd recommend eventually removing it from ejana as well.
