### ISSUE TITLE
Feature request: Multithreaded event source

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#72]
I'm putting pythia8 MC generator as an event source. It actually can work in multi-threaded environment - each thread can have its own pythia instance and generate events in parallel. 

How to implement this? 

As I understand EventSource is generically single threaded thing, as usually that is what is needed for IO. If I put it to Factory, how to live without an event source?

**Comment by nathanwbrei** [comment]
David and I discussed this earlier and agreed that multi-threaded event sources would be desirable and easy to implement. Hopefully I can get it in the next tagged release next week.

**Comment by nathanwbrei** [comment]
Closing this issue because is the same as #126.
