### ISSUE TITLE
Flags documentation 

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#8]
Can we have a valid documentation page with flags. ASAP please =)

like this (which I should probably throw out):
https://gitlab.com/eic/ejana/wikis/startup-arguments

P.S. While the documentation is a long process, this page would be very helpful.

**Comment by nathanwbrei** [comment]
I created a super basic "Installation+Use" page last week which discusses how to compile and run, including flags.

https://jeffersonlab.github.io/JANA2/Installation.html

**Comment by faustus123** [comment]
Documentation is a never ending issue. I'm closing this now assuming the immediate need has been met.
