### ISSUE TITLE
JEventProcessor::Finish() called too early

### ISSUE THREAD

**Issue by faustus123** [JeffersonLab/JANA2#87]
Ctl-C (i.e. sending SIGINT) to a running jana program causes the JEventProcessor::Finish() methods to be called immediately, even though there are still events being processed. It should probably defer calling Finish() until the events being actively processed are all finished.

More details:
 
While working with JANA v2.0.3 in the TriDAS setup in Hall-B, I made a plugin that implemented a JEventProcessor that opened a ROOT file in Init(), wrote to it in Process(), and closed it in Finish(). When I hit ctl-C to stop a process reading from a file, it immediately prints that the Finish() method was called (thereby closing the file), but then waits for a while for the threads processing events to finish. This eventually leads to a seg. fault since they try writing to the closed file.

**Comment by nathanwbrei** [comment]
Resolved by pull request #127
