### ISSUE TITLE
cmake does not honor g++/gcc in PATH

### ISSUE THREAD

**Issue by faustus123** [JeffersonLab/JANA2#91]
JANA2 failed to build against a version of root that was built using gcc5.3.0 with C++14. It turns out even though the g++ and c++ in my PATH pointed to gcc5.3.0, cmake still defaulted to the system gcc4.8.5. When I set the CXX and CC environment variables to point to gcc5.3.0 before running cmake, everything compiled just fine.

It seems PATH is not considered when building JANA2 which would be surprising for someone who set up to use a specific compiler with something like:

module load gcc/5.3.0

**Comment by nathanwbrei** [comment]
This looks like a deliberate design choice inside cmake that we can't do much about. I'd propose:

* Making sure that the gcc5.3.0 modulefile sets the CC and CXX envvars (I suspect other things may also break if these are omitted)
* Create an entry in the JANA FAQ telling the user to that they either need to set the CXX envar or pass -D CMAKE_CXX_COMPILER=g++-5.3.0 to cmake

**Comment by nathanwbrei** [comment]
I've added this to the documentation.
